BERT_IN_OUT = 300
BERT_HIDDEN = 300
BERT_NUM_LAYERS = 2
BERT_NUM_HEAD_EACH_LAYER = 4

PRETRAINING_FF_HIDDEN = 300
PRETRAINING_BATCH_SIZE = 100
PRETRAINING_EPOCH = 10

GAT_CONV_IN_CHANNEL = 100
GAT_CONV_OUT_CHANNEL = 20
GAT_CONV_HEADS = 5
GAT_CONV_NEGATIVE_SLOP = 0.1
GAT_CONV_DROPOUT = 0.1

GLOBAL_DATA_PATH = "./Data"
# MIMIC Files:
PRESCRIPTIONS = "PRESCRIPTIONS.csv"
ADMISSIONS = "ADMISSIONS.csv"
DIAGNOSIS_ICD="DIAGNOSES_ICD.csv"
# MIMIC Mapping Files
NDC_2_RXCUI_MAPPING = "ndc2rxnorm_mapping.txt"
RXCUI_2_ATC = "rxnorm2atc_level4.csv"

# Other File Names
UNIQUE_ATC_CSV= "unique-atc4.csv"
UNIQUE_ICD_CSV = "unique-icd.csv"
SINGLE_VISIT_DIAG_PKL = "single_visit_diag.pkl"
SINGLE_VISIT_MED_PKL = "single_visit_med.pkl"
MULTI_VISIT_PKL = "multi_visit.pkl"